### ISSUE TITLE
Import fails when all_tables=true on a SQL server database

### ISSUE THREAD

**Issue by danielholgate** [rjrudin/ml-migration-starter#15]
Error occurred when using the all_tables=true option against a SQL Server 2016 database. 
Can load individual tables when _all_tables=false_ without problems (haven't tried with other databases so not sure if this is a generic problem for the tool against SQL Server).

Sql server JDBC driver is mssql-jdbc-6.4.0.jre8.jar

When import is run it gets to the 87% mark and the process then does nothing for about 10 minutes 
```
12:45:23.402 [main] INFO  c.m.s.b.c.l.s.CommandLineJobRunner - JOB NAMES
12:45:23.404 [main] INFO  c.m.s.b.c.l.s.CommandLineJobRunner - job
12:45:23.968 [main] INFO  c.m.s.b.i.writer.MarkLogicItemWriter - MarkLogic v9.0-5
> Building 87% > :migrate
```
then the error appears. The exception is 
```
12:57:37.674 [main] ERROR o.s.batch.core.step.AbstractStep - Encountered an error executing step step1 in job migrateJob
org.springframework.batch.item.ItemStreamException: Failed to initialize the reader
...
Caused by: org.springframework.jdbc.BadSqlGrammarException: Executing query; bad SQL grammar [SELECT * FROM trace_xe_action_map]; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'trace_xe_action_map'.
```
Full stack trace from console is below:

```
MacPro-3447:ml-migration-starter dholgate$ ./gradlew migrate
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:loadH2Data
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:migrate
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/dholgate/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.1.8/e54f49a227611976642f81cf2106b81c1ece8bf5/logback-classic-1.1.8.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/dholgate/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.7.25/110cefe2df103412849d72ef7a67e4e91e4266b4/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
12:45:23.402 [main] INFO  c.m.s.b.c.l.s.CommandLineJobRunner - JOB NAMES
12:45:23.404 [main] INFO  c.m.s.b.c.l.s.CommandLineJobRunner - job
12:45:23.968 [main] INFO  c.m.s.b.i.writer.MarkLogicItemWriter - MarkLogic v9.0-5
12:57:37.674 [main] ERROR o.s.batch.core.step.AbstractStep - Encountered an error executing step step1 in job migrateJob
org.springframework.batch.item.ItemStreamException: Failed to initialize the reader
        at org.springframework.batch.item.support.AbstractItemCountingItemStreamItemReader.open(AbstractItemCountingItemStreamItemReader.java:147)
        at com.marklogic.spring.batch.item.rdbms.AllTablesItemReader.buildTableReader(AllTablesItemReader.java:145)
        at com.marklogic.spring.batch.item.rdbms.AllTablesItemReader.open(AllTablesItemReader.java:67)
        at org.springframework.batch.item.support.CompositeItemStream.open(CompositeItemStream.java:96)
        at org.springframework.batch.core.step.tasklet.TaskletStep.open(TaskletStep.java:310)
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy21.execute(Unknown Source)
        at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
        at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:392)
        at org.springframework.batch.core.job.SimpleJob.doExecute(SimpleJob.java:135)
        at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:306)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
        at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:128)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:127)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy17.run(Unknown Source)
        at com.marklogic.spring.batch.core.launch.support.CommandLineJobRunner.start(CommandLineJobRunner.java:387)
        at com.marklogic.spring.batch.core.launch.support.CommandLineJobRunner.execute(CommandLineJobRunner.java:564)
        at org.example.Main.main(Main.java:24)
Caused by: org.springframework.jdbc.BadSqlGrammarException: Executing query; bad SQL grammar [SELECT * FROM trace_xe_action_map]; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'trace_xe_action_map'.
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
        at org.springframework.batch.item.database.JdbcCursorItemReader.openCursor(JdbcCursorItemReader.java:131)
        at org.springframework.batch.item.database.AbstractCursorItemReader.doOpen(AbstractCursorItemReader.java:406)
        at org.springframework.batch.item.support.AbstractItemCountingItemStreamItemReader.open(AbstractItemCountingItemStreamItemReader.java:144)
        ... 38 common frames omitted
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'trace_xe_action_map'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:259)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1547)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:548)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:479)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7344)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2713)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:224)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:204)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:401)
        at org.springframework.batch.item.database.JdbcCursorItemReader.openCursor(JdbcCursorItemReader.java:126)
        ... 40 common frames omitted
12:57:37.683 [main] ERROR o.s.batch.core.step.AbstractStep - Exception while closing step execution resources in step step1 in job migrateJob
java.lang.NullPointerException: null
        at com.marklogic.spring.batch.item.writer.MarkLogicItemWriter.close(MarkLogicItemWriter.java:158)
        at org.springframework.batch.item.support.CompositeItemStream.close(CompositeItemStream.java:85)
        at org.springframework.batch.core.step.tasklet.TaskletStep.close(TaskletStep.java:305)
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:271)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy21.execute(Unknown Source)
        at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
        at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:392)
        at org.springframework.batch.core.job.SimpleJob.doExecute(SimpleJob.java:135)
        at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:306)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
        at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:128)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:127)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy17.run(Unknown Source)
        at com.marklogic.spring.batch.core.launch.support.CommandLineJobRunner.start(CommandLineJobRunner.java:387)
        at com.marklogic.spring.batch.core.launch.support.CommandLineJobRunner.execute(CommandLineJobRunner.java:564)
        at org.example.Main.main(Main.java:24)
:migrate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':migrate'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
Total time: 12 mins 17.348 secs
```

**Comment by rjrudin** [comment]
Pinging @sastafford

This project is intended to be an application starter kit, so it's expected to have to modify the source code. 

I think what you can do here is modify the AllTablesItemReader that's instantiated on line 81. That class has a setExcludeTableNames method that you can call to specify which table names to ignore. 

@sastafford An improvement here would be for AllTablesItemReader to default to logging an error instead of throwing one when it can't read from a table.

**Comment by danielholgate** [comment]
Tried excluding the table by doing this in MigrationConfig.java: 

```
java.util.Set<String> excludedTables = new java.util.HashSet<String>();
excludedTables.add("trace_xe_action_map");
((AllTablesItemReader)reader).setExcludeTableNames(excludedTables);
```

But got the same error. Still investigating.
